version: '3'

# --------------------------------------------- #

networks:
  alpha:

# --------------------------------------------- #

services:
  api:
    networks:
      - alpha
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 9999:9999
    environment:
      - PORT=9999
    depends_on:
      - db

# --------------------------------------------- #
  
  db:
    networks:
      - alpha
    image: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
     - POSTGRES_PASSWORD=pass1234

# --------------------------------------------- #
